name: "e_commerce_microservices"

services:
  catalog.db:
    image: postgres

  basket.db:
    image: postgres

  distributed.cache:
    image: redis

  order.db:
    image: mcr.microsoft.com/mssql/server

  message.broker:
    image: rabbitmq:management

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  yarp.api.gateway:
    image: ${DOCKER_REGISTRY-}yarp.api.gateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

  shopping.web:
    image: ${DOCKER_REGISTRY-}shopping.web
    build:
      context: .
      dockerfile: WebApps/Shopping.Web/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  redis_distributed_cache:
  rabbitmq_message_broker: